### ISSUE TITLE
Add relative custom location of docker-compose.yml per project

### ISSUE THREAD

**Issue by icasimpan** [docktie/docktie#11]
Up to this point, it is always assumed to be inside project directory https://github.com/icasimpan/docktie/blob/master/init.sh#L34
```
export DOCKTIE_DOCKER_COMPOSE_FULLPATH="$(pwd)/docker-compose.yml"
```
the "$(pwd)" part as it equates to where the docktie is initialized and is a known fact that it's always enforced from within the project dir:
```
## Enforce calling "init.sh" from within project directory.
##
DOCKTIE_DIR=$(dirname $0)
if [[ "$DOCKTIE_DIR" != "../docktie" ]]; then
    echo "ERROR: 'init.sh' must be called from within project directory."
    exit 1
else
    DOCKTIE_DIR="$(dirname $(pwd))/docktie"
fi
```

Sometimes, projects will be in separate subfolders so this has to be catered.
This should be named:
``
RELATIVE_DOCKERCOMPOSE_DIR
``
That should be defined in each project's `conf/*_env` file

**Comment by icasimpan** [comment]
Implemented. Closing.

**Comment by casimpania** [comment]
Implementation was buggy. Re-opening

**Comment by casimpania** [comment]
Confirmed latest bugfix working. Closing ticket.
