### ISSUE TITLE
Incorporate db backup mechanism

### ISSUE THREAD

**Issue by casimpania** [docktie/docktie#15]
See how it's done in https://ismael.casimpan.com/quicktasks/docker-mysql-backup-to-local/.

NOTE: In a version of docker-compose (1.26.2 or is it all of version 1?), `cp` command is not available and thus needs to downgrade to using the native `docker cp`.

**Comment by icasimpan** [comment]
Moved to https://github.com/docktie/docktie-ext/issues/1
